src/Entity/Destination.php
<?php

namespace App\Entity;

use App\Repository\DestinationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=DestinationRepository::class)
 */
class Destination
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $code_dest;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $des_dest;

    /**
     * @ORM\OneToMany(targetEntity=Ville::class, mappedBy="code_dest", orphanRemoval=true)
     */
    private $villes;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    public function __construct()
    {
        $this->villes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCodeDest(): ?string
    {
        return $this->code_dest;
    }

    public function setCodeDest(string $code_dest): self
    {
        $this->code_dest = $code_dest;

        return $this;
    }

    public function getDesDest(): ?string
    {
        return $this->des_dest;
    }

    public function setDesDest(?string $des_dest): self
    {
        $this->des_dest = $des_dest;

        return $this;
    }

    /**
     * @return Collection|Ville[]
     */
    public function getVilles(): Collection
    {
        return $this->villes;
    }

    public function addVille(Ville $ville): self
    {
        if (!$this->villes->contains($ville)) {
            $this->villes[] = $ville;
            $ville->setCodeDest($this);
        }

        return $this;
    }

    public function removeVille(Ville $ville): self
    {
        if ($this->villes->contains($ville)) {
            $this->villes->removeElement($ville);
            // set the owning side to null (unless already changed)
            if ($ville->getCodeDest() === $this) {
                $ville->setCodeDest(null);
            }
        }

        return $this;
    }
    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }
}

src/Entity/Ville.php
<?php

namespace App\Entity;

use App\Repository\VilleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=VilleRepository::class)
 */
class Ville
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $code_ville;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $des_ville;

    /**
     * @ORM\ManyToOne(targetEntity=Destination::class, inversedBy="villes", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $code_dest;

    /**
     * @ORM\OneToMany(targetEntity=EtapeCircuit::class, mappedBy="code_ville_etape", orphanRemoval=true)
     */
    private $etapeCircuits;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    public function __construct()
    {
        $this->etapeCircuits = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCodeVille(): ?string
    {
        return $this->code_ville;
    }

    public function setCodeVille(string $code_ville): self
    {
        $this->code_ville = $code_ville;

        return $this;
    }

    public function getDesVille(): ?string
    {
        return $this->des_ville;
    }

    public function setDesVille(?string $des_ville): self
    {
        $this->des_ville = $des_ville;

        return $this;
    }

    public function getCodeDest(): ?Destination
    {
        return $this->code_dest;
    }

    public function setCodeDest(?Destination $code_dest): self
    {
        $this->code_dest = $code_dest;

        return $this;
    }

    /**
     * @return Collection|EtapeCircuit[]
     */
    public function getEtapeCircuits(): Collection
    {
        return $this->etapeCircuits;
    }

    public function addEtapeCircuit(EtapeCircuit $etapeCircuit): self
    {
        if (!$this->etapeCircuits->contains($etapeCircuit)) {
            $this->etapeCircuits[] = $etapeCircuit;
            $etapeCircuit->setCodeVilleEtape($this);
        }

        return $this;
    }

    public function removeEtapeCircuit(EtapeCircuit $etapeCircuit): self
    {
        if ($this->etapeCircuits->contains($etapeCircuit)) {
            $this->etapeCircuits->removeElement($etapeCircuit);
            // set the owning side to null (unless already changed)
            if ($etapeCircuit->getCodeVilleEtape() === $this) {
                $etapeCircuit->setCodeVilleEtape(null);
            }
        }

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }
}

src/Form/VilleType.php
<?php

namespace App\Form;

use App\Entity\Destination;
use App\Entity\Ville;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class VilleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('code_ville')
            ->add('des_ville')
            ->add('code_dest',EntityType::class,[
                'class'=>Destination::class,
                'choice_label'=>'des_dest',
                'label'=>'destination'
            ])
            ->add('image')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Ville::class,
        ]);
    }
}

src/Controller/VilleController.php
<?php

namespace App\Controller;


use App\Entity\Destination;
use App\Entity\Ville;
use App\Form\DestinationType;
use App\Form\VilleType;
use App\Repository\DestinationRepository;
use App\Repository\VilleRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;


class VilleController extends AbstractController
{

    /**
     * @var VilleRepository
     */
    private $ville;

    /*
     * @var EntityManagerInterface
     */
    private $em;

    public function __construct(VilleRepository $ville, EntityManagerInterface $em)
    {
        $this->ville = $ville;
        $this->em = $em;
    }

    /**
     * @Route("/ville/{id}", name="ville")
     * @param Destination $des
     * @return Response
     */
    public function index(Destination $des): Response
    {
        $villes = $this->ville->findBy(['code_dest' => $des]);
        return $this->render('ville/ville.html.twig', [
            'controller_name' => 'VilleController',
            'villes' => $villes,
            'des' => $des
        ]);
    }

    /**
     * @Route("/ville/create/{id}", name="newVille")
     * @param Destination $des
     * @param Request $request
     * @return Response
     */
    public function newVille(Destination $des,Request $request):Response
    {
        $ville = new Ville();
        $ville->setCodeDest($des);
        $form = $this->createForm(VilleType::class,$ville);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $em1 = $this->getDoctrine()->getManager();
            $em1->persist($ville);
            $em1->flush();
            return $this->redirectToRoute('ville',['id' => $des->getId()]);
            //    return $this->redirectToRoute('ville/{id}');
        }

        return $this->render('administration/newVille.html.twig',[
            'des' => $des,
            'ville' => $ville,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/villeDelete/{id}/{des}", name="deleteVille")
     * @param Ville $ville
     * @param Destination $des
     * @param Request $request
     * @return RedirectResponse;
     */

    public function deleteVille(Ville $ville,Destination $des,Request $request):Response
    {
        if ($this->isCsrfTokenValid('delete'.$ville->getId(),$request->get('_token'))){
            $this->em->remove($ville);
            $this->em->flush();
        }
       return $this->redirectToRoute('ville',['id' => $des->getId()]);
    }


    /**
     * @Route("/editville/{id}/{des}", name="editVille")
     * @param Ville $ville
     * @param Destination $des
     * @param Request $request
     * @return Response
     */
    public function editVille(Ville $ville,Destination $des,Request $request):Response
    {


        $form = $this->createForm(VilleType::class,$ville);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $this->em->flush();
            return $this->redirectToRoute('ville',['id' => $des->getId()]);
        }

        return $this->render('administration/editVille.html.twig',[
            'des' => $des,
            'ville' => $ville,
            'form' => $form->createView()
        ]);
    }
}
?>

templates/ville/ville.html.twig
{% extends 'base.html.twig' %}

{% block title %}Villes{% endblock %}

{% block body %}
    <style>
        h2{color:cadetblue;text-align: center;font-weight: bold}
        .container{
            margin-top: 30px;
        }
        .container .image-container{
            margin-left: 27%;
            width: 500px;
        }
        .container #button{
            margin-left: 40%;
        }
        .container table tr th{
            text-decoration: underline;
            color: dodgerblue;
        }
        .container table img{
            border:solid 1px white;
            height: 120px;
            width: 150px;
        }
        .card-img{
            width: 40%;
            text-align: center;
            margin-left:auto;
            margin-right:auto;
        }
        a{
            color:#26a5d3;
        }
        a:hover,a:focus{
            text-decoration:none;
            color:#26a5d3;
        }
        .social a{font-size: 3em;padding: 2rem;}
        .fa-facebook{color: #3b5998;}
        .fa-twitter{color: #00aced;}
        .fa-google-plus-g{color: #dd4b39;}
        .fa-instagram{color: #517fa4;}
        .fa-youtube{color: #bb0000;}
        .fa-facebook:hover,.fa-twitter:hover,.fa-google-plus-g:hover
        ,.fa-instagram:hover,.fa-youtube:hover{color: #d5d5d5;}
        footer{margin-left:0px;width: 100%;background-color: #3f3f3f;color: #d5d5d5;padding-top: 2rem;}
        hr.light{border-top: 1px solid #d5d5d5;width: 75%;margin-top: .8rem;margin-bottom: 1rem;}
        footer a{color: #d5d5d5;}
        hr.light-100{border-top: 1px solid #d5d5d5;width: 75%;margin-top: .8rem;margin-bottom: 1rem;}
    </style>
    <div class="card bg-dark text-white">
        <img src="{{ des.image }}" class="card-img" alt="...">
        <div class="card-img-overlay">
            <h5 class="card-title">{{ des.desDest }}</h5>
            <p class="card-text">Code destination: {{ des.codeDest }}</p>
        </div>
    </div>
<div class="container">
    <table class="table table-striped table-dark">
    <thead>
    <tr>
        <th scope="col">Image ville</th>
        <th scope="col">Code ville</th>
        <th scope="col">Description ville</th>
        {% if app.user %}
        <th scope="col">Actions</th>
        {% endif %}
    </tr>
    </thead>
    <tbody>

    {% for ville in villes %}
        <tr>
            <td><a href="{{ ville.image }}"><img src="{{ ville.image }}"></a></td>
            <td>{{ ville.codeVille}}</td>
            <td>{{ ville.desVille }}</td>
            {% if app.user %}
            <td>
                <p style="display:inline-block">

                    <button class="btn btn-warning">
                        <a href="{{ path('editVille',{id: ville.id, des: ville.getCodeDest.id}) }}" style="color: white;" ><i class="far fa-edit"></i></a>
                    </button>&nbsp&nbsp&nbsp
                <form method="post" action="{{ path('deleteVille',{id: ville.id, des: ville.getCodeDest.id}) }}" style="display:inline-block"  onsubmit="return confirm('Etes vous sùr de supprimer')">
                    <input type="hidden" name="_method" value="DELETE">
                    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ ville.id) }}">
                    <button  class="btn btn-danger"><i class="far fa-trash-alt"></i></button>
                </form>

                </p>
            </td>
            {% endif %}
        </tr>

    {% endfor %}

    </tbody>
</table>
    {% if app.user %}
    <a href="{{ path('newVille',{id: des.id}) }}"><img style="width: 100px;width: 100px;margin-left: 40%" src="http://icons.iconarchive.com/icons/graphicloads/100-flat-2/256/add-icon.png">Ajouter une ville</a>
    {% endif %}
    <br>
    <button class="btn btn-secondary">
        <a href="{{ path('destination') }}" style="color: white;" ><i class="fas fa-undo-alt"></i> Retour</a>
    </button>&nbsp&nbsp&nbsp
</div>
    <br>
    <footer>
        <div class="container-fluid padding">
            <div class="row text-center">
                <div class="col-md-4">
                    <hr class="light">
                    <h1 style="font-family: Vivaldi;">ToursDSI22</h1>
                    <hr class="light">
                    <p>(+216) 27 132 456</p>
                    <p>(+216) 70 123 456</p>
                    <p> Email : ToursDSI22@gmail.com</p>
                    <p><i class="fas fa-map-marker-alt"></i> Ariana, Charguia</p>
                </div>
                <div class="col-md-4">
                    <hr class="light">
                    <h5>Menu</h5>
                    <hr class="light">
                    <a href="{{ path('destination') }}"><p>Destination</p></a>
                    <a href="{{ path('circuit') }}"><p>Circuit</p></a>
                    <a href="{{ path('contact') }}"><p>Contact</p></a>
                </div>
                <div class="col-md-4">
                    <hr class="light">
                    <h5>Suivez-nous</h5>
                    <hr class="light">
                    <div class="col-12 social padding">
                        <a href="#"><i class="fab fa-facebook"></i></a>
                        <a href="#"><i class="fab fa-twitter"></i></a>
                        <a href="#"><i class="fab fa-google-plus-g"></i></a>
                        <a href="#"><i class="fab fa-instagram"></i></a>
                        <a href="#"><i class="fab fa-youtube"></i></a>
                    </div>
                </div>
                <div class="col-12">
                    <hr class="light">
                    <h5>&copy;ToursDSI22 2020</h5>
                </div>
            </div>
        </div>
    </footer>
{% endblock %}