src/Entity/Circuit.php
<?php

namespace App\Entity;

use App\Repository\CircuitRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CircuitRepository::class)
 */
class Circuit
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $code_circuit;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $des_circuit;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $duree_circuit;

    /**
     * @ORM\OneToMany(targetEntity=EtapeCircuit::class, mappedBy="code_circuit_etape", orphanRemoval=true, cascade={"persist"})
     */
    private $etapeCircuits;

    public function __construct()
    {
        $this->etapeCircuits = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCodeCircuit(): ?string
    {
        return $this->code_circuit;
    }

    public function setCodeCircuit(string $code_circuit): self
    {
        $this->code_circuit = $code_circuit;

        return $this;
    }

    public function getDesCircuit(): ?string
    {
        return $this->des_circuit;
    }

    public function setDesCircuit(?string $des_circuit): self
    {
        $this->des_circuit = $des_circuit;

        return $this;
    }

    public function getDureeCircuit(): ?int
    {
        return $this->duree_circuit;
    }

    public function setDureeCircuit(?int $duree_circuit): self
    {
        $this->duree_circuit = $duree_circuit;

        return $this;
    }

    /**
     * @return Collection|EtapeCircuit[]
     */
    public function getEtapeCircuits(): Collection
    {
        return $this->etapeCircuits;
    }

    public function addEtapeCircuit(EtapeCircuit $etapeCircuit): self
    {
        if (!$this->etapeCircuits->contains($etapeCircuit)) {
            $this->etapeCircuits[] = $etapeCircuit;
            $etapeCircuit->setCodeCircuitEtape($this);
        }

        return $this;
    }

    public function removeEtapeCircuit(EtapeCircuit $etapeCircuit): self
    {
        if ($this->etapeCircuits->contains($etapeCircuit)) {
            $this->etapeCircuits->removeElement($etapeCircuit);
            // set the owning side to null (unless already changed)
            if ($etapeCircuit->getCodeCircuitEtape() === $this) {
                $etapeCircuit->setCodeCircuitEtape(null);
            }
        }

        return $this;
    }
}

src/Entity/EtapeCircuit.php
<?php

namespace App\Entity;

use App\Repository\EtapeCircuitRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EtapeCircuitRepository::class)
 */
class EtapeCircuit
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Ville::class, inversedBy="etapeCircuits", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $code_ville_etape;

    /**
     * @ORM\ManyToOne(targetEntity=Circuit::class, inversedBy="etapeCircuits", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $code_circuit_etape;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $duree_etape;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $ordre_etape;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCodeVilleEtape(): ?Ville
    {
        return $this->code_ville_etape;
    }

    public function setCodeVilleEtape(?Ville $code_ville_etape): self
    {
        $this->code_ville_etape = $code_ville_etape;

        return $this;
    }

    public function getCodeCircuitEtape(): ?Circuit
    {
        return $this->code_circuit_etape;
    }

    public function setCodeCircuitEtape(?Circuit $code_circuit_etape): self
    {
        $this->code_circuit_etape = $code_circuit_etape;

        return $this;
    }

    public function getDureeEtape(): ?int
    {
        return $this->duree_etape;
    }

    public function setDureeEtape(?int $duree_etape): self
    {
        $this->duree_etape = $duree_etape;

        return $this;
    }

    public function getOrdreEtape(): ?int
    {
        return $this->ordre_etape;
    }

    public function setOrdreEtape(?int $ordre_etape): self
    {
        $this->ordre_etape = $ordre_etape;

        return $this;
    }
}

src/Entity/Ville.php
<?php

namespace App\Entity;

use App\Repository\VilleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=VilleRepository::class)
 */
class Ville
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $code_ville;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $des_ville;

    /**
     * @ORM\ManyToOne(targetEntity=Destination::class, inversedBy="villes", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $code_dest;

    /**
     * @ORM\OneToMany(targetEntity=EtapeCircuit::class, mappedBy="code_ville_etape", orphanRemoval=true)
     */
    private $etapeCircuits;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    public function __construct()
    {
        $this->etapeCircuits = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCodeVille(): ?string
    {
        return $this->code_ville;
    }

    public function setCodeVille(string $code_ville): self
    {
        $this->code_ville = $code_ville;

        return $this;
    }

    public function getDesVille(): ?string
    {
        return $this->des_ville;
    }

    public function setDesVille(?string $des_ville): self
    {
        $this->des_ville = $des_ville;

        return $this;
    }

    public function getCodeDest(): ?Destination
    {
        return $this->code_dest;
    }

    public function setCodeDest(?Destination $code_dest): self
    {
        $this->code_dest = $code_dest;

        return $this;
    }

    /**
     * @return Collection|EtapeCircuit[]
     */
    public function getEtapeCircuits(): Collection
    {
        return $this->etapeCircuits;
    }

    public function addEtapeCircuit(EtapeCircuit $etapeCircuit): self
    {
        if (!$this->etapeCircuits->contains($etapeCircuit)) {
            $this->etapeCircuits[] = $etapeCircuit;
            $etapeCircuit->setCodeVilleEtape($this);
        }

        return $this;
    }

    public function removeEtapeCircuit(EtapeCircuit $etapeCircuit): self
    {
        if ($this->etapeCircuits->contains($etapeCircuit)) {
            $this->etapeCircuits->removeElement($etapeCircuit);
            // set the owning side to null (unless already changed)
            if ($etapeCircuit->getCodeVilleEtape() === $this) {
                $etapeCircuit->setCodeVilleEtape(null);
            }
        }

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }
}

src/Form/EtapeCircuitType.php
<?php

namespace App\Form;

use App\Entity\Circuit;
use App\Entity\EtapeCircuit;
use App\Entity\Ville;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EtapeCircuitType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('duree_etape')
            ->add('ordre_etape')
            ->add('code_ville_etape',EntityType::class,[
                'class'=>Ville::class,
                'choice_label'=>'des_ville',
                'label'=>'Ville'
            ])
            ->add('code_circuit_etape',EntityType::class,[
                'class'=>Circuit::class,
                'choice_label'=>'des_circuit',
                'label'=>'Circuit'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => EtapeCircuit::class,
        ]);
    }
}

src/Controller/EtapeCircuitController.php
<?php

namespace App\Controller;


use App\Entity\Circuit;
use App\Entity\EtapeCircuit;
use App\Form\CircuitType;
use App\Form\EtapeCircuitType;
use App\Repository\CircuitRepository;
use App\Repository\EtapeCircuitRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class EtapeCircuitController extends AbstractController
{
   /*
    * @var EtapeCircuitRepository
    */
    private $Etapecircuit;


    /*
     * @var EntityManagerInterface
     */
    private $em;

    public function __Construct(EtapeCircuitRepository $repository,EntityManagerInterface $em)
    {
        //Etapecircuit
        $this->Etapecircuit = $repository;
        //Entity manager
        $this->em = $em;
    }

    /**
     * @Route("/etapeCircuit/{id}", name="etapeCircuit")
     * @param Circuit $Circuit
     * @return Response
     */
    public function index(Circuit $Circuit): Response
    {
        $etapeCircuits = $this->Etapecircuit->findBy(['code_circuit_etape' => $Circuit]);
        return $this->render('etapecircuit/etapecircuit.html.twig', [
            'controller_name' => 'EtapeCircuitController',
            'etapeCircuits' => $etapeCircuits,
            'cir' => $Circuit
        ]);
    }

    /**
     * @Route("/etapeCircuit/create/{id}", name="newEtapeCircuit")
     * @param Circuit $cir
     * @param Request $request
     * @return Response
     */
    public function newEtapeCircuit(Circuit $cir,Request $request):Response
    {
        $etapeCircuit = new EtapeCircuit();
        $etapeCircuit->setCodeCircuitEtape($cir);
        $form = $this->createForm(EtapeCircuitType::class,$etapeCircuit);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $this->em->persist($etapeCircuit);
            $this->em->flush();
            return $this->redirectToRoute('etapeCircuit',['id' => $cir->getId()]);
        }

        return $this->render('administration/newEtapeCircuit.html.twig',[
            'cir' => $cir,
            'etapeCircuit' => $etapeCircuit,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/etapeCircuit/{id}/{cir}", name="editEtapeCircuit")
     * @param EtapeCircuit $etapeCircuit
     * @param Circuit $cir
     * @param Request $request
     * @return Response
     */
    public function editEtapeCircuit(EtapeCircuit $etapeCircuit, Circuit $cir, Request $request):Response
    {
        $form = $this->createForm(EtapeCircuitType::class,$etapeCircuit);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $this->em->flush();
            return $this->redirectToRoute('etapeCircuit',['id' => $cir->getId()]);
        }

        return $this->render('administration/editEtapeCircuit.html.twig',[
            'cir' => $cir,
            'etapeCircuit' => $etapeCircuit,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/etapeCircuitDelete/{id}/{cir}", name="deleteEtapeCircuit")
     * @param EtapeCircuit $etapeCircuit
     * @param Circuit $cir
     * @param Request $request
     * @return RedirectResponse;
     */
    public function deleteEtapeCircuit(EtapeCircuit $etapeCircuit, Circuit $cir, Request $request):Response
    {
        if ($this->isCsrfTokenValid('delete'.$etapeCircuit->getId(),$request->get('_token'))){
            $this->em->remove($etapeCircuit);
            $this->em->flush();
        }
        return $this->redirectToRoute('etapeCircuit',['id' => $cir->getId()]);
    }
}
?>

templates/etapeCircuit/etapeCircuit.html.twig
{% extends 'base.html.twig' %}

{% block title %}EtapeCircuits{% endblock %}

{% block body %}

    <style>

        main{margin-top: 68px;}
        h2{color:cadetblue;text-align: center;font-weight: bold}
        .container{
            margin-top: 30px;
        }
        .container table tr th{
            text-decoration: underline;
            color: dodgerblue;
        }
        .container table img{
            border:solid 1px white;
            height: 60px;
            width: 90px;
        }
        .card-text{
            margin-left:auto;
            margin-right:auto;
        }
        a{
            color:#26a5d3;
        }
        a:hover,a:focus{
            text-decoration:none;
            color:#26a5d3;
        }
        .social a{font-size: 3em;padding: 2rem;}
        .fa-facebook{color: #3b5998;}
        .fa-twitter{color: #00aced;}
        .fa-google-plus-g{color: #dd4b39;}
        .fa-instagram{color: #517fa4;}
        .fa-youtube{color: #bb0000;}
        .fa-facebook:hover,.fa-twitter:hover,.fa-google-plus-g:hover
        ,.fa-instagram:hover,.fa-youtube:hover{color: #d5d5d5;}
        footer{margin-left:0px;width: 100%;background-color: #3f3f3f;color: #d5d5d5;padding-top: 2rem;}
        hr.light{border-top: 1px solid #d5d5d5;width: 75%;margin-top: .8rem;margin-bottom: 1rem;}
        footer a{color: #d5d5d5;}
        hr.light-100{border-top: 1px solid #d5d5d5;width: 75%;margin-top: .8rem;margin-bottom: 1rem;}
    </style>

    <main>
        <hr>
        <h2>{{ cir.desCircuit }}</h2>
        <hr>
    </main>
    <div class="card bg-light">
        <div class="card">
            <p class="card-text">Durée du circuit : {{ cir.dureeCircuit }}</p>
            <p class="card-text">Code du circuit :  {{ cir.codeCircuit }}</p>
        </div>
    </div>
    <div class="container">
        <table class="table table-striped table-dark">
            <thead>
                <tr>
                    <th scope="col">Ville étape</th>
                    <th scope="col">Circuit étape</th>
                    <th scope="col">Duree étape</th>
                    <th scope="col">Ordre étape</th>
                    {% if app.user %}
                    <th scope="col">Actions</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
            {% for etape in etapeCircuits %}
                <tr>
                    <td>{{ etape.codeVilleEtape.desVille }}</td>
                    <td>{{ etape.codeCircuitEtape.desCircuit }}</td>
                    <td>{{ etape.dureeEtape }}</td>
                    <td>{{ etape.ordreEtape }}</td>
                    {% if app.user %}
                    <td>
                        <p style="display:inline-block">
                            <button class="btn btn-warning">
                                <a href="{{ path('editEtapeCircuit',{id: etape.id, cir: etape.getCodeCircuitEtape.id}) }}" style="color: white;" ><i class="far fa-edit"></i> </a>
                            </button>&nbsp&nbsp&nbsp
                            <form method="post" action="{{ path('deleteEtapeCircuit',{id: etape.id, cir: etape.getCodeCircuitEtape.id}) }}" style="display:inline-block"  onsubmit="return confirm('Etes vous sùr de supprimer')">
                                <input type="hidden" name="_method" value="DELETE">
                                <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ etape.id) }}">
                                <button  class="btn btn-danger"><i class="far fa-trash-alt"></i></button>
                            </form>
                        </p>
                    </td>
                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {% if app.user %}
        <a href="{{ path('newEtapeCircuit',{id: cir.id}) }}"><img style="width: 100px;width: 100px;margin-left: 40%" src="http://icons.iconarchive.com/icons/graphicloads/100-flat-2/256/add-icon.png"> Ajouter EtapeCircuit</a>
        {% endif %}
        <br>
        <button class="btn btn-secondary">
            <a href="{{ path('circuit') }}" style="color: white;" ><i class="fas fa-undo-alt"></i> Retour</a>
        </button>&nbsp&nbsp&nbsp
    </div>
    <br>
    <footer>
        <div class="container-fluid padding">
            <div class="row text-center">
                <div class="col-md-4">
                    <hr class="light">
                    <h1 style="font-family: Vivaldi;">ToursDSI22</h1>
                    <hr class="light">
                    <p>(+216) 27 132 456</p>
                    <p>(+216) 70 123 456</p>
                    <p> Email : ToursDSI22@gmail.com</p>
                    <p><i class="fas fa-map-marker-alt"></i> Ariana, Charguia</p>
                </div>
                <div class="col-md-4">
                    <hr class="light">
                    <h5>Menu</h5>
                    <hr class="light">
                    <a href="{{ path('destination') }}"><p>Destination</p></a>
                    <a href="{{ path('circuit') }}"><p>Circuit</p></a>
                    <a href="{{ path('contact') }}"><p>Contact</p></a>
                </div>
                <div class="col-md-4">
                    <hr class="light">
                    <h5>Suivez-nous</h5>
                    <hr class="light">
                    <div class="col-12 social padding">
                        <a href="#"><i class="fab fa-facebook"></i></a>
                        <a href="#"><i class="fab fa-twitter"></i></a>
                        <a href="#"><i class="fab fa-google-plus-g"></i></a>
                        <a href="#"><i class="fab fa-instagram"></i></a>
                        <a href="#"><i class="fab fa-youtube"></i></a>
                    </div>
                </div>
                <div class="col-12">
                    <hr class="light">
                    <h5>&copy;ToursDSI22 2020</h5>
                </div>
            </div>
        </div>
    </footer>
{% endblock %}